# Site settings
title: Curtis Murray
description: 'Data Scientist, PhD Candidate, Husband, Father-to-be'
url: 'http://curtis-murray.github.io'
baseurl: ''
profilepic: '/images/1.jpg'
bkimage: '/images/bk2.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'e9563652a9.js'

author:
  name: 'Curtis Murray'
  email: curtis@curtismurray.tech
  scholar: 25fFcUUAAAAJ
  twitter_username: curtis_w_murray
#  facebook_username: 
#  github_username:  curtis-murray
  linkedin_username:  curtiswmurray
#  meetup_name: 
  #ig_one: curtis_murray_
  #ig_two: curtis_murray_climbing

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
